service: ui-waflog-s3-bucket

frameworkVersion: "2"

plugins:
  - serverless-stack-termination-protection
  - serverless-deployment-bucket
  - serverless-s3-remover

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

  deploymentBucket:
    name: ${self:service}-${opt:stage, self:provider.stage}-deployment-bucket
    serverSideEncryption: AES256

custom:
  stage: ${opt:stage, self:provider.stage}
  serverlessTerminationProtection:
    stages:
      - master
      - val
      - production
      - develop
      - main
      - impl
      - val
      - prod

  deploymentBucket:
    versioning: true
  s3:
    slsbucket:
      name: ${self:service}-${opt:stage, self:provider.stage}-deployment-bucket
  remover:
    buckets:
      - ${self:custom.s3.slsbucket.name}

resources:
  Resources:
    WaflogsUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${AWS::AccountId}-${self:custom.stage}-waflogs
        VersioningConfiguration:
          Status: Enabled

  Outputs:
    WaflogsUploadBucketArn:
      Value: !GetAtt WaflogsUploadBucket.Arn
