service: ui-waflog-s3-bucket

frameworkVersion: "2"

plugins:
  - serverless-stack-termination-protection
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  deploymentBucket:
    name: ${file(./../../libs/accountId.js):accountId}-${self:service}-${self:custom.stage}-deployment-bucket
    maxPreviousDeploymentArtifacts: 1
    serverSideEncryption: AES256

custom:
  stage: ${opt:stage, self:provider.stage}
  serverlessTerminationProtection:
    stages:
      - master
      - val
      - production
      - develop
      - main
      - impl
      - val
      - prod
  deploymentBucket:
    versioning: true

resources:
  Resources:
    WaflogsUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${AWS::AccountId}-${self:custom.stage}-waflogs
        VersioningConfiguration:
          Status: Enabled

  Outputs:
    WaflogsUploadBucketArn:
      Value: !GetAtt WaflogsUploadBucket.Arn
