name: Deploy

on:
  push:
    branches:
      - gha*


jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1

    container:
      image:  circleci/node:12

    steps:
    - uses: actions/checkout@v1

    - run: ls -la
      working-directory: .
