name: Deploy

on:
  push:
    branches:
      - gha*

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 0

    container:
      image:  circleci/node:12

    steps:
    - uses: actions/checkout@v1

    - run: ./.github/github-lock.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: .

    - run: sleep 300
      working-directory: .
